# DB — Railway injects DATABASE_URL automatically
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT — set as Railway env variable
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000


# Mail — set as Railway env variables

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server
server.port=${PORT:8080}

# Swagger still works in prod
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs